server:
  port: 8082
  servlet:
    context-path: /user
spring:
  application:
    name: user-center
  main:
    # 解决Bean重复定义问题
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        #        server-addr: 106.54.77.31:8848
        ip: 127.0.0.1
        server-addr: 192.168.196.128:8848,192.168.196.129:8848,192.168.196.130:8848
  # mysql配置

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.196.128:3306/ykh_center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: junheroot123

  redis:
    port: 6379
    password: junheroot123
    host: 192.168.196.128
    jedis:
      pool:
        min-idle: 10
        max-idle: 20
        max-wait: -1ms
        max-active: 200


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.micro.ykh.dao.entity.*



  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

#发送短信验证码的配置
tencentsms:
  secretId: AKIDd1MRGp5H6sNq2xD5JI2f16leMo9gARyP
  secretKey: iDXkgRxcbD8amjRvHtj5A33uUzVYKzdv
  apps:
    - { sign: 房乐美, smsSdkAppid: 1400201952 }
    - { sign: 福物通, smsSdkAppid: 1400458675 }
  txtTemplates:
    - { code: sendVerificationCode, id: 385796 }